### ISSUE TITLE
Admin Logistics: New series was not created/linked to notes

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#108]
As previously discussed, when a new series image is uploaded: 

* a new series should be created on the video admin page
* the series should be linked to the notes on the notes admin page

Currently, no series image appears on the home screen because the notes are not associated with a series.

<img src=https://user-images.githubusercontent.com/48423418/97189948-8bdf1000-177b-11eb-8c20-d6a8f46cf453.PNG width=300>

This workflow should be resolved before the app officially launches.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588046293)

**Comment by lucastbelem** [comment]
@JonEsparaz this is good now.

Can you remind though - when does the series appear? Is it as soon as the notes are created?

**Comment by JonEsparaz** [comment]
I'm not sure I understand the question. What do you mean by the series? Are you wondering when the home screen changes?

**Comment by lucastbelem** [comment]
@JonEsparaz I think we're good now. Nevermind my question lol
The image appears.

**Comment by lucastbelem** [comment]
@deeinstereo although I wonder if it should be a different image. David, do you want the image to be the same size as the thumbnail that appears once there is an episode? Maybe we could use the full slide image of the series?
