### ISSUE TITLE
Staff Directory

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#110]
As per app design found in Figma, we need to create a staff directory in the app.

* [x] Ability to view staff directory by location or by last name
* [x] Ability to search staff directory by location or name
* [x] ~~If by location, staff members should be displayed by user's location first and then alphabetically~~
* [x] ~~Change button allowing user to change their preferred location~~
* [x] ~~Modal should popup~~
* [x] Call Button allowing the user to call the staff person directly from their phone dialer
* [x] Email button allowing user to email staff member on their preferred email client
* [x] Show "Staff Directory" in "More"
* [x] "View Teaching" button under each staff member who has teaching connected to them
* [ ] "All teachers" button taking user to teachers staff directory
* [x] Teachers' profiles should be clickable and take the user to a profile page for that staff member
* [x] Teachers' profile displays all teaching where that staff member was the teacher
* [x] Ability to search teachings by that teacher
* [ ] Display teacher's name on home page with latest teaching (clickable to teacher's profile)

All mentions of "site" in the app should be instead "parish". 

@GeorgeBellTMH, do the teacher pieces require backend work? I remember you saying that there is something we need to do to make it so we can assign teachers to teachings.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588046235)

**Comment by GeorgeBellTMH** [comment]
Yes it requires us to add the admin piece...and then you need to enter all the data...

Other questions for staff/etc:

Do you want to include a way to search/see the overseers
Do you want to include a way to search/see the coordinators etc.

It's probably best to do all of this at the same time...

Suggest for coordinators we show them under "XXX Site Team" in "More" if the person has selected a site...XXX is the site name...

So the menu would have:

Overseers
Staff Directory
Burlington Site Team

Or something like that...

**Comment by lucastbelem** [comment]
Let's do this:

- [ ] Add "Overseers Directory" (data in overseers.json)

Coordinators are already searchable as part of the staff team. When a part selects a site, their staff team appears first in the directory, so I think we're covered here.

**Comment by lucastbelem** [comment]
@itbel staff without a location/parish/site should only appear in the view/search by last name to be in line with the website. They should not show up by location.

**Comment by lucastbelem** [comment]
@deeinstereo what do you think of @GeorgeBellTMH idea about a menu item under more for "My Parish Team"? I like the idea a lot, but I'm thinking about how it impacts the UX we do have. Currently, coordinators for a site appear under that site when the staff directory is being viewed by location. If we add that menu item, do we remove that person's parish team from the staff directory and only show other parishes? Or do we show in both places?

**Comment by deeinstereo** [comment]
@lucastbelem let's chat more about this in the next digital update meeting. I like the idea of calling it a Parish Team. We call it a team on the website now. One thing I want to make sure we do is not include the coordinator roles understaff, it gives the perception that we have a lot of staff when in reality they are 99% volunteer roles. 
Let's chat more! But I do like it!

**Comment by lucastbelem** [comment]
@deeinstereo ok sounds good. We'll chat on Monday.

If that's the case, it might actually make the thing simpler. 

Staff Directory (staff only)
Parish Team

**Comment by itbel** [comment]
~~Not every staff member belongs to a physical location. Some people belong to "Communications", or "Youth" for example.~~ ~~Should they be omitted from the "By Location" view?~~
Edit: oops i missed a comment.

**Comment by lucastbelem** [comment]
@deeinstereo can you please confirm this plan. This is what George suggested. I think it's great.

- [ ] Staff Directory page: only shows people in the staff.json data file. Searchable by name or location.
- [ ] My Parish Team page: only shows people for the particular parish user selected as his or her own. Display staff member for that parish from staff.json data file and coordinators for that parish from coordinators.json data file. If user doesn't have a parish selected, do not display My Parish Team. 
- [ ] Overseers page: only shows people from the overseers.json data file. They are not staff nor are they associated with a parish.

**Comment by GeorgeBellTMH** [comment]
It might be worth thinking about combining this all into one page...I’m just concerned about the last page getting overloaded with options. 

Ie maybe have “Our Team”...then three options inside that include as filters:

Staff Team
Parish Team
Overseers

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I like that way more than having 3 buttons on the "more" page.

@deeinstereo would this effectively just bring us back to the original design, but where the titles are different? What I mean is that "Parish Team" could be the "locations" filter in the design, showing your parish first followed by all of the other parishes. That's the original design, just changes the language.

**Comment by lucastbelem** [comment]
@itbel closing the loop on this.

2 buttons - Staff Team and My Parish Team. Staff team should only show staff, no filter for location. My Parish Team should only show the user's selected parish team, which includes staff for that parish and coordinators.

No overseers.

**Comment by lucastbelem** [comment]
> * If by location, staff members should be displayed by user's location first and then alphabetically
> * [ ]  Change button allowing user to change their preferred location

As per the latest changes, these 2 deliverables are cancelled.
