### ISSUE TITLE
Event fixes - add to calendar

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#112]
Add to calendar doesn't appear for all events. See images below for 1 event with "add to calendar" and another without.
![Screenshot_20201028-094336_The Meeting House](https://user-images.githubusercontent.com/48295718/97453921-94b31b80-190c-11eb-8b09-825afe43b5e2.jpg)
![Screenshot_20201028-094542_The Meeting House](https://user-images.githubusercontent.com/48295718/97453930-95e44880-190c-11eb-8368-91f86777132e.jpg)

**Comment by itbel** [comment]
Some events do not have an ending time entered. Even though the event might have a start and end time in the description, this does not show in the correct field. It is not possible to create an event without an ending time. I believe this could be a data entry issue.
A possible fix for events without an ending time can be to create reminders instead of events but this only works on iOS. There is no equivalent mechanism available in expo-calendar on Android.

**Comment by lucastbelem** [comment]
@itbel Just to confirm - it's just a matter of us entering end times in the facebook event itself?

And if an event has no end time, we cannot have the "add to calendar" button there? Correct?

**Comment by itbel** [comment]
Yes.
If there is no end time entered it cannot be added as an event to the calendar.
As you can see, some events have no entry for end_time.
`Object {
  "description": "Calling all our KIDMAX Families! We are hosting a special DRIVE-THRU Halloween PARADE on Saturday, October 31st from 1-2pm. 
........
Hope to see you all!",

  "end_time": null,                                 <-----------------------------------------------------------
  "event_times": null,
  "id": "669919587284568",
  "name": "Drive-Thru Halloween Parade",
  "place": Object {
    "id": null,
    "location": null,
    "name": "1240 Advance Rd, Burlington, ON L7M 1G6, Canada",
  },
  "start_time": "2020-10-31T13:00:00-0400",
}`

**Comment by lucastbelem** [comment]
@deeinstereo can we train our people to add an end time?

**Comment by deeinstereo** [comment]
@lucastbelem yes! Let's mention it at WASM and send an urgent email reminder afterwards to all pastors.

**Comment by lucastbelem** [comment]
@deeinstereo perfect!

I'm closing this issue then.

**Comment by GeorgeBellTMH** [comment]
Another way to do it would be to just default events without a value to one hour long...
