### ISSUE TITLE
Tight view on iOS

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#115]
I just did a quick test on a small iPhone and noticed that some titles are a bit too long for the screen and the comment icon doesn't show properly. Here is an image for reference.

![46854](https://user-images.githubusercontent.com/48295718/97462600-49513b00-1915-11eb-8fe6-8bfb11f81f0e.jpg)

JonEsparaz tagging you as you worked on that piece mostly for whenever you have time, but let me know if I should pass this one off to someone else.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588046114)

**Comment by JonEsparaz** [comment]
I probably can't get around to this until reading week (starts Nov 9). Feel free to pass this off if the timeline doesn't work.

**Comment by lucastbelem** [comment]
Sounds good (thanks for responding so quickly!). I'll leave it here and if we get to it soon, I'll close it. Otherwise, it'll stay open for a while - not top priority atm.
