### ISSUE TITLE
Events - Online urls

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#120]
When an event is set to "online" on Facebook, the user is given the option of adding an external url. We'll train our people to enter their zoom links in that field. Can we make it so that when the event is pulled to the app, it looks for that url and creates a button that says "attend event"? This is the same situation as has already been implemented for "register", but looking at a different facebook field.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588045907)

**Comment by itbel** [comment]
This is still not showing on my end. Data was entered for this event on FB. Any ideas? @GeorgeBellTMH 

![missingData](https://user-images.githubusercontent.com/42515854/99093012-efe93d00-259f-11eb-8fad-c8276ee81020.png)

**Comment by GeorgeBellTMH** [comment]
Ok it should be showing up now....

**Comment by GeorgeBellTMH** [comment]
Also cover photos are now showing up as well!
