### ISSUE TITLE
Should FB events be fetched only at certain times?

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/mobile#125]
I've been working on making Livestream events only fetchable once per day.
Should something similar also be done for the FB events data? Currently every time the user returns to the homepage a query is made.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588675026)

**Comment by lucastbelem** [comment]
Once a day may be too few for events. Maybe 3 times a day?

For livestream, I think that works.
