### ISSUE TITLE
Should past event instances be omitted from showing for an ongoing event?

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/mobile#126]
#### Should past event times be shown here for ongoing events such as this? deeinstereo
![Screenshot!UNITO-UNDERSCORE!20201103-132509!UNITO-UNDERSCORE!Expo](https://user-images.githubusercontent.com/42515854/98025814-2ffa3400-1dd8-11eb-94b0-09bef38f58b4.jpg)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588704931)

**Comment by deeinstereo** [comment]
@itbel nope! Past dates should be removed.
