### ISSUE TITLE
Add Parry Sound to Instagram feed pull

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#130]
Parry Sound now has an instragram account. Can we get their account to pull to their parish page on the app?

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=589308796)

**Comment by GeorgeBellTMH** [comment]
This is now added to the script we run on the web...it should be picked up tomorrow...I've also added it to the app.

**Comment by lucastbelem** [comment]
Perfect, thanks.

Talking about that - what do we need to do to make instagram appear at
sites pages? Is there dev work remaining?

**Comment by georgevicbell** [comment]
On the web. Yes. Someone needs to write it. Should be a day or two or work.

Sent from my iPhone

On Nov 4, 2020, at 8:48 PM, Lucas Belem <notifications@github.com> wrote:

﻿

Perfect, thanks.

Talking about that - what do we need to do to make instagram appear at
sites pages? Is there dev work remaining?
