### ISSUE TITLE
Realtime Menu Customization

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#136]
It would be good to have the menu customizable via a JSON file that is picked up from the website.

* [x] Ability to add/remove custom links 
* [x] Ability to add/remove content only pages
* [ ] Ability to add/remove in-app pages (so we can hide staff, or change the name of it)
* [ ] Ability to change this all without re-deploying
* [ ] New features as needed

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=594932527)

**Comment by lucastbelem** [comment]
@itbel did any of this get addressed through your latest work?

**Comment by lucastbelem** [comment]
@itbel

**Comment by itbel** [comment]
I think this is referring to the newly built JSON content feature. #317. If this is just referring to the More screen, there is a JSON file that allows for customization of that screen, but it is limited in comparison to #317

**Comment by itbel** [comment]
The plan was to eventually use the same functionality in the more screen...
