### ISSUE TITLE
Profile Improvements

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#146]
Profiles are pretty bare bones right now. Suggest we add a few features over time:

* [ ] ability to turn on/off notifications
* [ ] ability to add a profile image (use functionality from JC)
* [ ] ability to pick/save a home-church
* [ ] donation stuff
* [ ] validate phone and email
* [ ] ability to send notifications by email, txt or push
* [ ] historical notes
* [ ] remember what you've watched/read
* [ ] groups (either self-selected or generated from internal data)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=595575476)

**Comment by lucastbelem** [comment]
Tracking ideas somewhere else so git doesn't get overloaded.
