### ISSUE TITLE
Series Graphics pre 2009

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#147]
Would be good to get series graphics for pre-2009...are we still working on this?

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=595639541)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH yeah, we have them...they just need to be uploaded. I'll get someone on that in the new year. I have this task in wrike.
