### ISSUE TITLE
Live Feature - improvements

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#149]
Can we make it so that the app picks up any and all live events? I.e. Christmas eve is coming up and we'll have 3 live services.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=596024680)

**Comment by itbel** [comment]
I believe this should already be working. We just might need to make changes to the "going live soon" and "live now" messages, as well as omit the notes section if there won't be any.

**Comment by lucastbelem** [comment]
@itbel 

- [ ] Can you use the banner message for the yellow bar in the app as it is in the web?
- [ ] Can you remove omit notes sections from events without notes?

**Comment by deeinstereo** [comment]
Sure. I think it's more of a screen takeover on the app if you click the yellow bar similar to what happens on the website.

**Comment by lucastbelem** [comment]
@itbel Please prioritize the first 2 requests...I'm opening a separate one for the third one.
