### ISSUE TITLE
Speaker Carousel

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#157]
As per design found here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=97%3A4946

* [x] Display carousel including picture, name, and "all teachers" button
* [x] All teachers button should let the user see a page just like the staff directory, but displaying only teachers.
* [x] Include a list of speakers from within our staff
* [x] Include speakers who are not part of our staff
* [x] Allow administrators to "hide" speakers from carousel.
* [x] When staff speakers are hidden, they do not show up in the carousel AND their staff listing does not get a "view teaching" button

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=603236861)

**Comment by GeorgeBellTMH** [comment]
Would you like to sort by:
- Alpha First or Last name?
- Number of videos?
- Something else? (Staff, Guests) etc.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH good question!!

I'd go with most popular...but that's probably too complicated (i.e. of all videos for a teacher, how many views does that teacher have in total?)

That being too complicated, I'd go with number of videos. The logic being that Bruxy has the most videos because he teachers the most, so therefore, he's likely to be looked for the most.

@deeinstereo thoughts?

**Comment by deeinstereo** [comment]
I think sort my number of videos makes the most sense. Thanks!
