### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#158]
As per design here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=223%3A168, we need a module to display announcements to our communities.

* [x] Display announcements on home screen when announcements exist
* [x] Announcements should be displayed based on the user's Parish selection as well as cross regional announcements. 
* [x] If no parish is selected, only display cross regional announcements.
* [x] Display announcement icon on each announcement
* [x] Announcements should include image, title and description.
* [x] Ability to click on announcement and see longer description.
* [x] The first portion of the description should be populated on the announcement on the home screen followed by an ellipses as needed.
* [x] Ability to include a call to action button in announcements that only displays when a call to action exists.
* [x] Ability to create announcements for all parishes
* [x] Ability to create parish-specific announcements
* [x] Ability to add images to announcements

@GeorgeBellTMH I see this as a separate tab in admin, alongside blogs, notes, livestream, etc. In figure, we'll likely give pastors and others access to announcements.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=603844301)

**Comment by GeorgeBellTMH** [comment]
Should announcements also send notifications? If yes or optionally:

- [ ] content of notification
- [ ] time to send
- [ ] action when opened
