### ISSUE TITLE
Feature request: Note-taking

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#16]
As per approved design here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=311%3A14503. 

We need to develop the functionality around note-taking.

**Comment by GeorgeBellTMH** [comment]
It should work with the old legacy notes, as well as the new website notes...likely we need to migrate the old notes...priority is new notes, migration of old notes can happen later.

**Comment by JonEsparaz** [comment]
@lucastbelemm, @deeinstereo and I discussed and we will leave out rich text on comments for now and potentially forever, but if it's something people really want, we can make the transition at some point.

**Comment by lucastbelem** [comment]
Amazing!
