### ISSUE TITLE
Migrate existing user notes

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#160]
We want to migrate user notes from our old app to the new app.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=603861909)

**Comment by GeorgeBellTMH** [comment]
@lucastbelem can you reach out to Curtis and get the final export of the old notes dB? We will have to do the following:

- [x] get Db from Curtis
- [ ] import into dynamo
- [ ] link up with existing videos and email/users
- [ ] read only interface for old notes

Potentially we make it also editable, but I think at this point that may not be necessary.

**Comment by GeorgeBellTMH** [comment]
No longer relevant...
