### ISSUE TITLE
Teaching header

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#164]
The teaching header that is currently implemented is on a transparent background. It's supposed to turn solid on scroll. Image attached for reference.
![](https://user-images.githubusercontent.com/48295718/100934972-80d77800-34bd-11eb-9d95-ce0681bc5327.png)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=603878208)

**Comment by JonEsparaz** [comment]
I implemented this previously, so more recent changes likely broke this functionality.

**Comment by lucastbelem** [comment]
@itbel can you take a look?

6.0.3 (Nov 4) works. 
6.0.6 (Nov 29) doesn't. 

It looks like it happened with one of the releases that's still in test. Either staff, livestream, or events.

Thanks team!

**Comment by JonEsparaz** [comment]
@itbel, I think the `useLayoutEffect()` hook is the issue since it will only fire once, so the opacity of the header isn't updating dynamically.

**Comment by itbel** [comment]
Just need to either remove the dependency array or add the changing values to it to make it update. I'll get right on it
