### ISSUE TITLE
"Series you might like"

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#166]
As per design here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=99%3A9075.

Series you might like or recommended series, or something else. This appears at the bottom of every series page. Should we use the logic on the website for "popular series"? The drawback to this is that no matter what series you click on, the content for "series you might like" is the same.

Another way we could do this is to add keywords to series (development required) and then create some kind of logic to customize "series you might like" based on keyword alignment.

deeinstereo GeorgeBellTMH thoughts?

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=603890498)

**Comment by GeorgeBellTMH** [comment]
Popular can be done quickly. I would suggest we do that first. There is also recommended which we are in the progress of doing for blogs, but requires some setup and we need at least 1000 data points to train it on.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH popular already exists on the app and web. :)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH gotcha now. Let's implement it as popular for now then and go from there.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH does it make more sense to add popular series to the a series page or the overall teaching page?

**Comment by GeorgeBellTMH** [comment]
I'd actually like to do a rethink of the video pages a bit. 

It would be nice if you and David could configure things yourself a bit (like on the website) and we could provide a bit more flexibility over time...

Along with that I'd like to figure out how to get more of the videos, playlists, suggestions, kids and extra video content etc. into the app...right now we are missing a lot of content. 

My suggestion is we work to make it so you guys can do the following:

- Configure the three existing icons/pages with components
- configure the menu screen
- configure video section with some more pages (perhaps via a dropdown)
- potential to add one or more buttons to bottom of the screen
- potential for the menu screen to have sub pages
- host all of these on the website as json files so we can dynamically update them
