### ISSUE TITLE
Staff Team, Parish Team, Teachers Improvements

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/mobile#174]
As pointed out by JonEsparaz , Figma requires BottomTabNavigator to not display on these screens: 

* [x] `StaffList.tsx`, `ParishTeam.tsx`, and `TeacherProfile.tsx` to be moved to `AppNavigator.tsx`. 
* [ ] `StaffItem.tsx` and `TeacherItem.tsx` could be merged
* [ ] `TeacherProfile.tsx` proper pagination for videos
* [x] `StaffItem.tsx` content overlapping on smaller devices. #156
* [ ] `StaffDirectoryService.ts` static typing missing

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=605295517)

**Comment by GeorgeBellTMH** [comment]
There is a bug where if you click on Danielle Stricklands name, then click on the house in the bottom left, then click on the three dots in bottom right you end up in the wrong place (click back does not resolve)...is that related to this?

**Comment by itbel** [comment]
Is this issue still occurring?

**Comment by lucastbelem** [comment]
@itbel the bug George mentioned persists. Can you tackle the bug and this overall issue?

**Comment by lucastbelem** [comment]
@itbel

**Comment by GeorgeBellTMH** [comment]
Can't reproduce...
