### ISSUE TITLE
Issue when clicking on Danielle Stricklands name from homepage

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#177]
![](https://user-images.githubusercontent.com/47749730/102391364-9bbce880-3fa3-11eb-9f47-3d5b57b24708.png)

I think there is a problem with the list of teaching for some people

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=610847077)

**Comment by itbel** [comment]
Ok. I'm on it
