### ISSUE TITLE
Update Events Page Date Graphic

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/mobile#180]
Keep centred but align to bottom of image instead of centre of image (to help reveal the picture behind). 
Eg. On marriage preparation workshop move the Feb 19 box to align with the bottom of the picture of the couple.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=612898091)

**Comment by itbel** [comment]
Do we want the date box below the picture or overlapping?
![Screenshot_20201222-141040_Expo](https://user-images.githubusercontent.com/42515854/102924467-9a863280-445f-11eb-825a-0004dd71a31b.jpg)
![Screenshot_20201222-141049_Expo](https://user-images.githubusercontent.com/42515854/102924470-9a863280-445f-11eb-850e-4fe8cab189fa.jpg)

**Comment by deeinstereo** [comment]
@itbel  This looks great! Is it overlapping a little now? Whatever you did in the Marriage retreat event. That's what I want. 

Thanks!

**Comment by itbel** [comment]
(They are both overlapping)
Alright cool.
