### ISSUE TITLE
Add Teaching Highlights to Series

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/mobile#181]
Below all the episodes add Highlights section and pull from the teaching highlights for said section.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=612898934)

**Comment by lucastbelem** [comment]
@itbel these should look the same as the teaching in a series page, but show under a heading called "Highlights".

**Comment by itbel** [comment]
This has been worked on in PR #222, but there is an issue with highlights that is causing crashes.  Issue #224 Needs to be looked at before PR #222 can be merged
