### ISSUE TITLE
Speakers - Admin

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#183]
I need the ability to delete speakers from the admin interface.

A bonus would be to be able to edit them.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=613068480)

**Comment by lucastbelem** [comment]
@itbel to clarify - I'd like to be able to both remove a speaker from a video as well as delete that speaker from our list of speakers.

**Comment by itbel** [comment]
done
