### ISSUE TITLE
Duplicates of Tim Day's Teaching 

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/mobile#184]
Some of the video teaching appears twice under Tim's name, giving the illusion that there are far more videos that there are in reality. 

* A different Inner Motivation x2 (Almost Normal, January 2015)
* New Support (Inside Out, January 2013)
* Preeminence of Mercy (Ordinary Radicals August 2012)
* Passion for God's Righteousness (Ordinary Radicals August 2012)
\-

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=613388431)

**Comment by itbel** [comment]
deleted duplicates
