### ISSUE TITLE
Recent teaching date/time logic bug

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#191]
The Christmas Eve service is displaying on the home screen instead of today's teaching (Dec 27).

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=614925341)

**Comment by itbel** [comment]
Is this a data entry issue?
The Christmas eve video has been added to the Sunday teaching playlist.

**Comment by JonEsparaz** [comment]
I believe it is in the correct playlist. Good Friday will also produce the same issue.

We need to check if the date is a Sunday. 

I'll fix this and write a unit test so we don't have regressions in the future.

**Comment by GeorgeBellTMH** [comment]
We are now running tests on GitHub…there are a couple that aren’t working…but should be more useful now that they run on PR’s.

G

**Comment by JonEsparaz** [comment]
I saw that in the web repo - good stuff! Probably should add a similar workflow to this repo.

Side note: I think the existing tests in this repo are out of date, so you can probably remove them.
