### ISSUE TITLE
Improved fallback image for when there is no series

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#197]
![](https://user-images.githubusercontent.com/47749730/103431772-9d8dcb00-4ba3-11eb-83e9-526377498522.png)

Need a better image to go here when series doesn't have a graphic.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=616430258)

**Comment by JonEsparaz** [comment]
A better fallback image is definitely needed, but there's still an underlying data entry issue (as mentioned previously: #108).

I think uploading images via the admin page when a video series is created would be the ideal solution. It's pretty easy to setup a Lambda that resizes the images after they are uploaded to the S3 bucket, so we'd still be able to use scaled images.

**Comment by deeinstereo** [comment]
This is pretty close to the fallback I'd want though. Simple black and white with the logo. What are the specs so that I can update it to clean it up a little?

**Comment by JonEsparaz** [comment]
@deeinstereo here's the current image: https://www.themeetinghouse.com/static/NoCompassionLogo.png. It's square for some reason, which is incorrect. 

The image should be 528x624. I actually made a fallback image specifically for the app already: https://www.themeetinghouse.com/static/photos/series/series-fallback-app.jpg. We use this in other parts of the app.

If the image I made is up to standard, we can just switch out the URL. If not, let us know when the new image is ready.

**Comment by deeinstereo** [comment]
@JonEsparaz super odd. That no compassion one is supposed to be used only when there is a compassion partner that doesn't have a logo. 

As far as the fallback you made, that's perfect for mobile, but it wouldn't work for website because of how the white on white would look. I would invert it for web. 

Other than that it looks great!

**Comment by JonEsparaz** [comment]
I made a black background version, which is used on the website: https://www.themeetinghouse.com/static/photos/series/series-fallback.jpg

I'll swap out the image in the app.
