### ISSUE TITLE
Allow users to signup or beta

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#207]
We should add a link on the menu at the bottom - Sign up for Beta...

On iOS it should link to: https://testflight.apple.com/join/y06dCmo4
On Android it should link to: https://play.google.com/store/apps/details?id=org.tmh.takenote

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=620733676)

**Comment by GeorgeBellTMH** [comment]
@lucastbelem  this was quick, so I just did it while I was publishing today...please check copy/icon are ok...

**Comment by lucastbelem** [comment]
Looks and works good :)
