### ISSUE TITLE
Announcements - 1 more thing

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#212]
The Call to action button permanently says "call to action". Can we get a text field to edit what that button should say? With a character limit so that the text in the button is never longer than 1 line?

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=621402089)

**Comment by lucastbelem** [comment]
@itbel can you work on this please?

**Comment by itbel** [comment]
ok
