### ISSUE TITLE
Revisit Notes access UI with Jen

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#220]
We've got some real user feedback about the notes button on the website not being very visible at first pass, and people not knowing they can click on it, especially when there is a big send questions button right then and there. 

Let's get Jen Au to take a look at the UI.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=625604183)

**Comment by GeorgeBellTMH** [comment]
Is this for mobile or web?

**Comment by lucastbelem** [comment]
This was supposed to be for the website.
