### ISSUE TITLE
Implement live events drop down in the app

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#223]
┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=628983025)

**Comment by GeorgeBellTMH** [comment]
Basically this should use the same logic as the website...

**Comment by lucastbelem** [comment]
Clicking on the yellow "live" bar should trigger a dropdown as it does on the website so that when we have multiple events, they are displayed on app too.
