### ISSUE TITLE
Improve Ask a Question feature when not signed in

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#226]
Two potential approaches:

* Have a modal when the screen _mounts_ (similar to the comments screen) that prompts users to sign up/sign in. It would be mega annoying to type out a long question, then click send, get an error alert and lose the contents of my message.
* Detect when a user is not logged in and add an input field for email address.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=629603528)

**Comment by GeorgeBellTMH** [comment]
@deeinstereo which way would you prefer to handle this? Logging in to ask a question seems a pretty heavy ask...

**Comment by deeinstereo** [comment]
@GeorgeBellTMH that's true. I want to make this as accessible as possible, but also want to have a follow up if need be. Can we just add the email as a required field, and then you can submit a question? Also gives us a chance to follow up with people if it's appropriate.
