### ISSUE TITLE
Staff tests are failing

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#229]
Tests in `staff.test.js` are failing. Issue is with `<CachedImage/>` from [react-native-expo-cached-image](https://www.npmjs.com/package/react-native-expo-cached-image).

Error message: Check the render method of CachedImage.

@itbel assigning you because you probably know the most about this package.

The issue could be with the package itself, or something external. If the issue is with the package, you could:

* mock the component
* find a different/better package
* submit an issue/PR to get the package fixed

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=637226203)

**Comment by itbel** [comment]
I'll look into it when I get a chance.

**Comment by JonEsparaz** [comment]
Seems like this resolved itself. NPM probably did something weird in https://github.com/themeetinghouse/mobile/commit/1db9bbef83e081bf8dc72d46e84f5dba433ad4a2.
