### ISSUE TITLE
Filter videos from Instagram component

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#238]
Related to https://github.com/themeetinghouse/web/issues/689.

Videos need to be filtered out.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=651242386)

**Comment by JonEsparaz** [comment]
Example: only 7 results show here because the video errors out.

<img src=https://user-images.githubusercontent.com/48423418/109709087-260bf600-7b6a-11eb-9adf-3bad9095f316.png width=300>

**Comment by deeinstereo** [comment]
Good catch! I think this is a new error... videos would play in the past

**Comment by JonEsparaz** [comment]
> Good catch! I think this is a new error... videos would play in the past

The old implementation did not include videos at all.
