### ISSUE TITLE
Push notifications are delayed by one hour

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#246]
Jen McWilliams reported this on over on [Discord](https://discord.com/channels/766847785768583169/814215193701515304/833355126319349852).

Push notification came in at 5 mins before 11am (instead of 5 mins before 10am).

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=676298449)

**Comment by GeorgeBellTMH** [comment]
Fixed....we will have to update this every time we change from EST to EDT...
