### ISSUE TITLE
Timezones for Homechurch

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#251]
We need to put the time into the users local time. The data should be loaded in the f1 query.

Suggest using the global home churches as test (everything else will likely be in EST).

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=696878278)

**Comment by GeorgeBellTMH** [comment]
While you are doing this, please also do it in the web....https://github.com/themeetinghouse/web/issues/760

**Comment by itbel** [comment]
I'll look into it.

**Comment by GeorgeBellTMH** [comment]
Thanks! I think the website handles timezones in the live header and live video page...so should be able to make use of moment-timezone and the code there.
