### ISSUE TITLE
[Android] Homechurch map does not open

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/mobile#254]
Pressing the "Map" button in `<HomeChurchScreen />` crashes the app instead of opening `<HomeChurchMapScreen />`
The issue does not occur in development. 

Is it possible we are missing some [configuration](https://docs.expo.io/versions/latest/sdk/map-view/#configuration)? @GeorgeBellTMH 

I updated react-native-maps to latest version in #255, unable to test as the crash is not occurring in development. 

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=699792000)

**Comment by GeorgeBellTMH** [comment]
I believe this is fixed.
