### ISSUE TITLE
Homechurch issues

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#256]
* [ ] Not all the homechurches are showing on the map (ie sandbanks)
* [x] When filtering by specific areas the map doesn't filter.
* [x] There is no way to see the location of a homechurch when you are on the list view (clicking on it should take you to the map)
* [x] In list view "Clear All" button is not always clearing location selection

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=701521849)

**Comment by itbel** [comment]
Locations that aren't showing on the map screen are missing location data. @Lucastbelem
These locations are also missing map markers on [themeetinghouse.com/find-homechurch](https://themeetinghouse.com/find-homechurch)

**Comment by itbel** [comment]
- Barrie, Ontario Home Church appears under Global

Several home churches are missing location data

No Coordinates
GMT1900 Online Home Church - 7pm UTC +0   3130530
West Lake Home Church   2944897
The Screen Porch Online Home Church - 7pm UTC -6   3131473
Logan Online Home Church   2797860
Belleville Home Church   2818025
Wesley Acres Home Church   2797843
Upside Down Online Home Church - 8pm UTC +13   3130531
Trenton Home Church   3088986
Kotsopoulos Online Home Church   3055217
Online Home Church - 7pm UTC +8   3131501
Upper Zoom Online Home Church - 7pm UTC -6   3086111
Kingston Home Church   3089542

**Comment by GeorgeBellTMH** [comment]
Can we close?

**Comment by itbel** [comment]
> Can we close?

Location data is still missing for several home churches.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH @itbel  how do I fix this?

**Comment by GeorgeBellTMH** [comment]
It might be helpful for online churches to pick a location in their timezone to be visible on the map...otherwise, the online homechurches just won't show up, and we can close this...

**Comment by GeorgeBellTMH** [comment]
But the solution is to add location data in F1...

**Comment by itbel** [comment]
Data is still missing but feature working as intended otherwise.

**Comment by lucastbelem** [comment]
Considering it fixed for now.
