### ISSUE TITLE
Implement TikTok....

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#260]
The idea of this ticket is that we would have a TikTok like interface in the app (to watch and swipe short videos) - which we would then be able to share, or click through and watch full teaching...

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=706733592)

**Comment by GeorgeBellTMH** [comment]
cc: @deeinstereo @lucastbelem

**Comment by georgevicbell** [comment]
@GarnetMason this ticket may be interesting to you, it was an idea we had a while ago to implement a TikTok style interface in the app...potentially if you are looking to get support to do TikTok type videos this could be a way to make them visible in more than just TikTok...

**Comment by GarnetMason** [comment]
This sounds awesome, it could be a feed of a combination of the short teaser clips from the teaching series plus engagement clips created by our pastoral teams, I would love to thing though this a bit more and see what we can do with it!
