### ISSUE TITLE
❌ App is pulling old events with past dates

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/mobile#261]
Check out Waterloo's feed. They are getting events from months ago. These should be cleared by now.
![IMG!UNITO-UNDERSCORE!74B8430FD7A3-1](https://user-images.githubusercontent.com/47831068/122791670-6dd49b80-d287-11eb-8a7a-1b3e70a84712.jpeg)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=709491839)

**Comment by itbel** [comment]
These appear to be ongoing events. I will look into it

**Comment by GeorgeBellTMH** [comment]
Fixed
