### ISSUE TITLE
Show F1 Groups on My Account page

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#269]
To help with debugging users it would be great if on the My Account page we had a field for groups with a list of tags 

Groups: [Admin] [Elder] [Staff]

We can hide [Participant]

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=746214583)

**Comment by itbel** [comment]
Something like this?
<img width="300px" src="https://cdn.discordapp.com/attachments/435595076631003136/883434089691115541/image.png"/>

**Comment by georgevicbell** [comment]
Yup, but with bubble tags or instead of [ ]

**Comment by itbel** [comment]
Okay I will style them.
