### ISSUE TITLE
Teaching: Teachers

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#27]
As per approved design here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=136%3A2351.

Clicking on a teacher, should land the user on a page as the design above. The page includes basic info on the teacher and all teachings by that teacher.

Clicking on "All teachers" should take the user to a page similar to the all staff page.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588059282)

**Comment by GeorgeBellTMH** [comment]
We will need to make sure the list of teachers is updated in dynamo...I'm not sure if we fully did that because on the web we didn't want this feature...

**Comment by GeorgeBellTMH** [comment]
We may also need to add an interface on the web to ensure sermons are tagged going forward.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH My guess as you say that is that we'd have retroactively tag all teaching with the teacher, correct?

**Comment by GeorgeBellTMH** [comment]
Some was already done, but then we stopped.

**Comment by GeorgeBellTMH** [comment]
#110
