### ISSUE TITLE
Announcement updates

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#270]
* please remove the character limit from the announcements. On the home screen, the announcement should continue to get cut off so only the first 4 lines or so are shown, but when the user clicks on the announcement, they should be able to see a much longer version. I know I asked for the character limit, but in the way we're using announcements now, well, it's better not to have a limit.
* images don't populate. Something to do with the url returned.

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=746781050)

**Comment by lucastbelem** [comment]
@itbel could you please prioritize this one? Character limit is the most important one.

**Comment by lucastbelem** [comment]
@itbel image?

**Comment by itbel** [comment]
- [x] Removed character limit from announcement page.
- [ ] Image fix

**Comment by lucastbelem** [comment]
@itbel what's left here?

**Comment by itbel** [comment]
Working on fixing images now...

**Comment by itbel** [comment]
Fixed as per [#1090](https://github.com/themeetinghouse/web/pull/1090)
