### ISSUE TITLE
Live bar issue?

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#274]
On my phone (where I have the beta version installed) I do not see the "we are live now" bar. 

On Mandie's phone (where she has the public version installed) I do see the live bar.

Any ideas why?

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=751561432)

**Comment by itbel** [comment]
The live bar works on both iPhone and Android for me. Can you confirm this issue is still occurring after updating the app?
