### ISSUE TITLE
At least 1 user reports not seeing a specific app link

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#281]
If anyone goes to the "more" menu (under the 3 dots) the first item they should see is "sunday registration". One user who is on an iPhone 12 Pro, iOS 15, reports that this link does not appear for her.

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=770581331)

**Comment by itbel** [comment]
Custom menu request must be failing and falling back to default menu (which doesn't include registration). Not sure why it would be failing. Works fine on my iPhone. Is the registration link missing every time?

**Comment by itbel** [comment]
Need more info on this. 
1. Is the issue still occurring? 
2. Does the specific link fail to load every time?

**Comment by lucastbelem** [comment]
Closing for tests of next version.
