### ISSUE TITLE
User doesn't receive verification code to create app account

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#286]
GeorgeBellTMH I sent you the users email address via email.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=797472134)

**Comment by itbel** [comment]
Sign up flow is fixed and verification works!

Now that verification is enabled, would signed in unverified users have been booted from their account? 

We may have a number of users who signed up in the last few months who are not verified and might be having issues accessing all features within the app if they are still logged in, but not verified.

Maybe we should also create a modal to let users know that they need to login and verify their account.

Thoughts?

@GeorgeBellTMH

**Comment by lucastbelem** [comment]
@itbel I wonder if this is still relevant, and if so, let's do it.
