### ISSUE TITLE
Determine which App admin features will be on the website, and which will need to be in-app or separate.

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#29]
Where possible lets make sure the website admin can do everything needed in the app. 

-Featured items
-Notes
-New Video Features

etc.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588059661)

**Comment by lucastbelem** [comment]
website admin should manage the following (for existing app design):

- Events
- Announcements
- Notes
- Videos
- Staffing updates

**Comment by JonEsparaz** [comment]
For the current week's teaching (before the YouTube video is up) we need a way to add:
- [x] Episode title*
- [x] Episode description*
- [ ] Name of teacher*
- [x] If there's a new series, we need to be able to create the series and upload the series graphics (@lucastbelem and I discussed this and it shouldn't be an issue after some fixes)

*Can probably be added to notes so the Sunday morning team can do it all in one place

Other content (week number, date) we should have and/or can determine programmatically.

**Comment by GeorgeBellTMH** [comment]
Closing for #27
