### ISSUE TITLE
6.0.15 Testing

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#291]
Let me know when complete.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=836826826)

**Comment by GeorgeBellTMH** [comment]
Mostly just version upgrades...

**Comment by lucastbelem** [comment]
Teaching screen appears to be missing the rightmost quarter (or be just a black strip covering everything underneath it).

**Comment by itbel** [comment]
> Teaching screen appears to be missing the rightmost quarter (or be just a black strip covering everything underneath it).

This and a bunch of other issues introduced in this version have been fixed.
