### ISSUE TITLE
Sign up and login feature

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#3]
As per approved design found here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=146%3A7146.

**Comment by georgevicbell** [comment]
Using same cognito db as on web.

Sent from my iPhone

On Jul 22, 2020, at 5:38 PM, Lucas Belem <notifications@github.com> wrote:

﻿

As per approved design found here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=146%3A7146.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH we need a custom Congito attribute for home site.
