### ISSUE TITLE
Scripture not loading in the app

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#313]
![Uploading Screenshot 2022-03-03 at 8.21.28 PM.png…]()

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=883889781)

**Comment by itbel** [comment]
Appears to be working for me. Pls re-up the screenshot.

**Comment by lucastbelem** [comment]
It links to the right place but it doesn't display in the app.

**Comment by lucastbelem** [comment]
![Screenshot_20220426-123242.png](https://user-images.githubusercontent.com/48295718/165337847-7f7f02dd-4102-4f8f-bcfb-d7e3a906ad0f.png)

**Comment by itbel** [comment]
On it.

**Comment by itbel** [comment]
Verses not getting added to Notes
Last verse in dynamo is from January (?)

**Comment by georgevicbell** [comment]
Is this fixed?

**Comment by lucastbelem** [comment]
Still an issue.

**Comment by itbel** [comment]
Fixed.
