### ISSUE TITLE
Add ability to build screens with json

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/mobile#316]
* [x] Structure app renderRouter similarly to tmh-web renderRouter 
* [ ] Ability to change bottom tab items order
* [ ] Ability to hide bottom tab items
* [x] Create new bottom tab item for "featured"
* [x] Featured bottom tab item should link to screen with links to screens built with renderRouter

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=888662373)

**Comment by GeorgeBellTMH** [comment]
- [ ] Use the last downloaded JSON if offline, handle 404 or being offline and unable to download json with a "this content is unavailable" page...
- [x] Some pageConfig ability (hide bottom bar, hide top bar, top bar title, hide profile icon, show back button)
- [x] Bonus config (white/black background)
- [ ] Various components - Hero, various image+text, link list, video

It would be good if we could duplicate some of the website pages easily (by using the same json) - like about us and location pages...

**Comment by itbel** [comment]
short WIP demo

https://user-images.githubusercontent.com/42515854/165872538-307ee008-0d9f-4f89-8a34-3ef2e9b0a7e0.mp4

**Comment by itbel** [comment]
I'm going to write docs for this
