### ISSUE TITLE
YouTube vs MP4 playback

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#32]
We need to determine if video playback should happen via embedding a YouTube player or using the MP4 files hosted in the cloud. YouTube player will sacrifice some design elements, MP4 is potentially expensive. @GeorgeBellTMH, thoughts?

**Comment by GeorgeBellTMH** [comment]
I prefer YouTube for a bunch of reasons - cost, and keeping stats in one place being the two major reasons.

**Comment by GeorgeBellTMH** [comment]
I'm ok using mp4 for offline viewing if that becomes a thing, but we need to be smart about bandwidth.

**Comment by JonEsparaz** [comment]
Will use YouTube via [react-native-youtube-iframe](https://www.npmjs.com/package/react-native-youtube-iframe).
