### ISSUE TITLE
Chat in app

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#321]
Would be cool to include the YouTube chat in the app along side the notes...This could be used on Sunday mornings to chat in real-time while the service is happening.

Should use YouTube api instead of embed so that it looks native.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=892509945)

**Comment by georgevicbell** [comment]
I think we should close this in favour of discord...
