### ISSUE TITLE
Test Log

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#365]
@laurengermain let me know if you have access to TestFlight or the beta's on android...if not I can hook you up...

**Comment by GeorgeBellTMH** [comment]
- [x] #362 
- [x] #361 
- [x] #360 
- [x] #355 
- [x] #353

**Comment by GeorgeBellTMH** [comment]
Also did a bunch of patches...

**Comment by GeorgeBellTMH** [comment]
Building now...should be on TestFlight in a couple minutes...

**Comment by laurengermain** [comment]
@GeorgeBellTMH I do not have access to TestFlight. Let me know what I need to do to get setup!

**Comment by lucastbelem** [comment]
@laurengermain are you iphone? If so, I believe test flight is an app you download to test the beta version of the app.

**Comment by laurengermain** [comment]
#361 app crashes when I try to select the map on the Home Church Finder
@GeorgeBellTMH

**Comment by lucastbelem** [comment]
@itbel

**Comment by itbel** [comment]
> #361 app crashes when I try to select the map on the Home Church Finder 

@GeorgeBellTMH

Fixed in #369

**Comment by GeorgeBellTMH** [comment]
- [x] https://github.com/themeetinghouse/mobile/pull/371
- [x] https://github.com/themeetinghouse/mobile/pull/370
- [x] version upgrades

**Comment by lucastbelem** [comment]
How does Lauren test version upgrades?

**Comment by GeorgeBellTMH** [comment]
Just a general test is fine…the main changes required were to the header…

G

**Comment by lucastbelem** [comment]
- [x] https://github.com/themeetinghouse/mobile/pull/370
@laurengermain

**Comment by itbel** [comment]
- [x] #378

**Comment by laurengermain** [comment]
Not sure if this is related to #371 or not but on the teaching page, the carousels are only displaying 1 video at a time. There are also 2 kids/youth videos appearing?
![Screen Shot 2023-02-14 at 10 16 32 AM](https://user-images.githubusercontent.com/89869101/218780067-81a25dfb-702e-4800-8716-42dea9a59310.png)
![Screen Shot 2023-02-14 at 10 16 17 AM](https://user-images.githubusercontent.com/89869101/218780247-51523d7d-476a-4c7e-9f1b-5bde1fbb5777.png)

**Comment by itbel** [comment]
> Not sure if this is related to #371 or not but on the teaching page, the carousels are only displaying 1 video at a time. There are also 2 kids/youth videos appearing? 

https://github.com/themeetinghouse/web/pull/1149 fixes the carousel issue. 
as for the archive, there is nothing wrong code-wise... I moved the video out of the playlist but i'm not sure about the "Test" video.
