### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#37]
Are we targeting tablets on the Google Play and/or the App Store? If so, should the UI just scale (probably won't look very nice) or should we take the approach of Instagram and just crop the width to have it look and behave as if it was a phone?

**Comment by georgevicbell** [comment]
I’d suggest that we try to scale it, and then for specific experiences (live, video and homepage) we try to make it work well on iPad (ie video and notes side by side). Some of the other experiences can just be left as scaled/very similar to iPhone.

Sent from my iPhone

On Aug 10, 2020, at 5:04 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

Are we targeting tablets on the Google Play and/or the App Store? If so, should the UI just scale (probably won't look very nice) or should we take the approach of Instagram and just crop the width to have it look and behave as if it was a phone?

**Comment by JonEsparaz** [comment]
I'll spend a day or two adapting everything to tablet once the beta launch functionality is all complete. Luckily we only support portrait orientation, so everything just needs to be adaptive, but not responsive (don't need event listeners).

**Comment by JonEsparaz** [comment]
I think this is ok now. Was more of a question than an issue anyways.
