### ISSUE TITLE
Livestream not working

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/mobile#377]

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can you pls publish @itbel fix for this as soon as possible? @laurengermain can you pls test as soon as George lets you know that it's fixed?

Thanks.

**Comment by lucastbelem** [comment]
- [ ] Create livestream
- [ ] Check that everything shows up on the app
- [ ] Can you watch?
- [ ] How does the UI look?

**Comment by laurengermain** [comment]
@lucastbelem tested on the website and all seems to be working. Someone else will need to test the app as I cannot change the time on my phone :)
