### ISSUE TITLE
My profile and account settings features

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#4]
As per approved design found here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=238%3A1928. 

The user needs to be able to access his/her comments from note-taking, as well as account settings from this window. 
These windows should appear when the person icon on the top right is clicked on. User should also be able to see and change their location from here.

**Comment by georgevicbell** [comment]
Login should use the same cognito as we have on web.

Sent from my iPhone

On Jul 22, 2020, at 5:43 PM, Lucas Belem <notifications@github.com> wrote:

﻿

As per approved design found here: https://www.figma.com/file/EHr4QEEBfkAe9T5OTcVXah/Native-App?node-id=238%3A1928.

The user needs to be able to access his/her comments from note-taking, as well as account settings from this window.
These windows should appear when the person icon on the top right is clicked on. User should also be able to see and change their location from here.
