### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#40]
We are required to have the privacy policy in-app by Apple and Google.

Did the old app have a privacy policy we can re-use/update? If not the website privacy policy is likely sufficient with some modifications.

**Comment by GeorgeBellTMH** [comment]
@lucastbelem we may need to have this soon to get past the review process...

**Comment by GeorgeBellTMH** [comment]
Never mind, I found the link...
