### ISSUE TITLE
Smooth scrolling vs locked scrolling on Series

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#51]
I think we should use smooth/inertial scrolling since there are so many series, it would take forever to scroll one-by-one to the end...

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588048400)

**Comment by JonEsparaz** [comment]
Can’t you just click “all series” if you want to get to the end quickly?

Also, I’ve got a PR coming where I fixed the scroll parameters, so it
should be easier to scroll, but the carousel still snaps.

**Comment by JonEsparaz** [comment]
We can see how things are after #52. Switching to smooth scroll might take time as I'll have to re-work the animations.

**Comment by lucastbelem** [comment]
@itbel here is a fun improvement to look into.

**Comment by itbel** [comment]
Closing due to the fact that we no longer have many series... as per @lucastbelem
