### ISSUE TITLE
Orientation lock not working in Test Flight

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#53]
On the Test Flight app, I can rotate my phone 90 degrees and the orientation of the app changes. This behaviour is not reflected on the Expo client (testing on iOS).

Our app.json config is correct, so this might just be a Test Flight bug or we need to lock orientation at runtime.

**Comment by georgevicbell** [comment]
I just changed it. It should be fixed.

Sent from my iPhone

On Aug 24, 2020, at 9:28 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

On the Test Flight app, I can rotate my phone 90 degrees and the orientation of the app changes. This behaviour is not reflected on the Expo client (testing on iOS).

Our app.json config is correct, so this might just be a Test Flight bug or we need to lock orientation at runtime.

**Comment by JonEsparaz** [comment]
Ok thanks.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH just looking at app.json. Shouldn't it be `"orientation": "portrait"` not `"orientation": "default"`?
