### ISSUE TITLE
Cognito attribute for scripture link preference

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#55]
Used for this dialogue:

<img src=https://user-images.githubusercontent.com/48423418/91361387-2d6ed300-e7c6-11ea-93b4-e25f8686ed35.png width=30% >

I'll add something in the settings page too.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH did you get a chance to add this?

**Comment by GeorgeBellTMH** [comment]
custom:preference_openBible
