### ISSUE TITLE
No spaces in icon on iOS

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#61]
┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588047819)

**Comment by JonEsparaz** [comment]
Can we make the app icon say "TMH" or "TMH App" or "TMH Mobile" so it doesn't get truncated?

**Comment by GeorgeBellTMH** [comment]
@deeinstereo this is your call...

**Comment by deeinstereo** [comment]
What about these options:
- MeetingHouse
-Meeting House
- TMH

I don't think we need to add APP to TMH, TMH Mobile might also be nice. I'd really need to see how it looks before making a final call. What do you guys think?

**Comment by GeorgeBellTMH** [comment]
Meeting House will be better for search I think. 

Note it's only where it shows the name below the icon where it is truncated right now...it's fine on search pages and in any place where the name is to the right of the icon.

**Comment by deeinstereo** [comment]
Hey, just to close the loop after chatting with Jon, so we can actually run The Meeting House for both app stores, and then once they download it the truncated name will be MeetingHouse

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can we close this?
