### ISSUE TITLE
Activity indicators in sign-up/sign-in

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#63]
Some asynchronous processes take a while, so we should let the user know something is happening (otherwise it looks like the app is frozen).

**Comment by lucastbelem** [comment]
@JonEsparaz how much work is this one?

**Comment by JonEsparaz** [comment]
An hour tops.

**Comment by lucastbelem** [comment]
@JonEsparaz awesome! Let's add this as part of our bug fixes releases. Sound cool?
