### ISSUE TITLE
Paginate All Series and All Teaching screens

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#64]
Right now, everything is loaded, which is fine for new devices, but pagination would improve performance and reduce bandwidth costs (for us and the user).

I'll need to figure out the best way to query teaching by date to achieve this. Elasticsearch might work better than filters and key directives.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588047667)

**Comment by JonEsparaz** [comment]
Somewhat related to #69

**Comment by lucastbelem** [comment]
Closing for now...most content was removed.
