### ISSUE TITLE
Patch Lambda to handle Series graphics (filenames with spaces)

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#65]
Images load painfully slow on the All Series screen. Probably because they are ~5x bigger than they need to be.

**Comment by GeorgeBellTMH** [comment]
Does the existing one not work?

**Comment by JonEsparaz** [comment]
Sorry should've been more specific...

https://www.themeetinghouse.com/cached/320/static/photos/series/adult-sunday-The%20Missing%20Peace.jpg doesn't seem to point to a file, and I believe this is the same issue as https://github.com/themeetinghouse/web/issues/390.

There seems to be something wrong when the filename has spaces. Can you confirm if the files are actually in the bucket?

**Comment by GeorgeBellTMH** [comment]
Not on s3...

**Comment by GeorgeBellTMH** [comment]
Gonna try a fix...

**Comment by GeorgeBellTMH** [comment]
K it's working now...
