### ISSUE TITLE
Fix memory leaks

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#69]
Need to add a clean up to some of the `useEffect()` calls on the teaching screens.

There shouldn't be major issues (ie crashes), but this does affect performance.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588047268)

**Comment by lucastbelem** [comment]
This is old, so maybe already done?

**Comment by itbel** [comment]
No, this issue is still present.
