### ISSUE TITLE
Initial test bugs

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#74]
As discussed in our meeting:

- Some app functionality was not working (i.e. clicking on a sermon did nothing, but then when it did, I couldn't watch or listen.
- Then I removed and reinstalled the app. But that resulted in an older version being installed.

**Comment by JonEsparaz** [comment]
If the first bug persists after a clean install, I'll look into it, but it sounds like you're having issues downloading the app itself.

The second issue is more of a George thing.

**Comment by lucastbelem** [comment]
The app corrected itself in terms of it being the latest version, so the George issue is solved.

However, I'm still not getting some things to work:

- [x] Clicking on a series (i.e. Rebuilding the Church) took 3 or 4 clicks (maybe a performance issue?)
- [x] Then clicking on a sermon doesn't open the sermon at all. It flashes to indicate that I've clicked on it, but nothing happens. (let me know if you want to see a screenshot video of the experience).
- [x] Share button opens up a small popup. Then, if I click on the "share" icon in there, nothing happens.
- [x] When creating an account, if I type my email and password and then select my location, once I do select the location, my email and password inputed disappear.
- [x] Error message "password not long enough" doesn't fully appear. Image attached.
- [x] Again, maybe just be a performance issue, but I needed to click "login" 3 or 4 times before it logged in. My guess is that it worked at the first click, but took time to do its thing. If that's the case, could we add a "loading" animation or even icon to let the user know their request worked?
- [x] This is minor, but when creating a tag during commenting, user is told to separate tags with with a comma, which makes perfect sense. But then the tag is saved with the comma.

**Comment by lucastbelem** [comment]
Samsung Galaxy S8.
![Screenshot_20200916-073355_tmh-mobile](https://user-images.githubusercontent.com/48295718/93332698-39134f80-f7f0-11ea-9ce9-dcfed9485543.jpg)

**Comment by JonEsparaz** [comment]
> This is minor, but when creating a tag during commenting, user is told to separate tags with with a comma, which makes perfect sense. But then the tag is saved with the comma.

If you look carefully at the Figma mockups, this is the "desired" behaviour, but we can change it up...
![image](https://user-images.githubusercontent.com/48423418/93363361-1fd0ca00-f815-11ea-8228-4bebfba8fddb.png)

**Comment by JonEsparaz** [comment]
> Again, maybe just be a performance issue, but I needed to click "login" 3 or 4 times before it logged in. My guess is that it worked at the first click, but took time to do its thing. If that's the case, could we add a "loading" animation or even icon to let the user know their request worked?

See #63 (duplicate).

**Comment by JonEsparaz** [comment]
> > This is minor, but when creating a tag during commenting, user is told to separate tags with with a comma, which makes perfect sense. But then the tag is saved with the comma.
> 
> If you look carefully at the Figma mockups, this is the "desired" behaviour, but we can change it up...

I mis-interpreted this. Will fix...

**Comment by JonEsparaz** [comment]
> Share button opens up a small popup. Then, if I click on the "share" icon in there, nothing happens.

Note to self: unhandled Promise.

**Comment by JonEsparaz** [comment]
@lucastbelem the share pop up has some significant issues on Android that are difficult (probably impossible) to fix unless Android/React Native stop sucking. The text options pop up on notes also have some issues (you can click, but if the button you are clicking is on top of a link or other touchable element, both will be activated).

Rather than spending several hours trying to fix the unfixable, here's my proposed re-design. I never really liked the pop up component, and it's bad UX practice anyways since stuff at the top of the screen is difficult to reach on large devices.

Proposed solution: place the dialogue for both share and text options at the bottom of the screen. Notable apps that do this: Facebook, Twitter, Instagram for share, YouVersion for text options.

I will echo the design of the "How would you like to open this verse" dialogue, which is already placed at the bottom of the screen.

**Comment by lucastbelem** [comment]
Sounds like a good plan. I think that for this iteration anyways, it sounds
like it's either cut it out altogether, or go with a solution like what you
proposed.

For notes, to make sure I follow, you're talking about the aA button?

**Comment by JonEsparaz** [comment]
Yeah the aA button.

**Comment by JonEsparaz** [comment]
@lucastbelem here's what the button of the screen dialogues look like: 

<div>
<img width=35% src=https://user-images.githubusercontent.com/48423418/93660024-e668ac00-fa18-11ea-881b-afcebeadd49b.PNG>
<img width=35% src=https://user-images.githubusercontent.com/48423418/93660025-e668ac00-fa18-11ea-9cfb-dc02e76e8d36.PNG>
<div>

We've got more space now too, which is nice, so we can add more share options and perhaps a show/hide comments button for text options.

**Comment by JonEsparaz** [comment]
About the remaining two bugs:

> Clicking on a series (i.e. Rebuilding the Church) took 3 or 4 clicks (maybe a performance issue?)

I can't reproduce unfortunately, and I'm not too sure about this being a perf issue. It's possible that the image is blocking the component from fully mounting, so perhaps a poor internet connection? (Would be improved by #72). 

> Then clicking on a sermon doesn't open the sermon at all. It flashes to indicate that I've clicked on it, but nothing happens. (let me know if you want to see a screenshot video of the experience).

So I built an APK using the code at https://github.com/themeetinghouse/mobile/pull/77/commits/57289ef4dd95ec7f9e98ad41d2228c1b6d136dc4 using `expo-cli@3.27.6` and it runs without issue on an Pixel 3 emulator running Android 10.0. Hopefully this issue will resolve itself in the next release, if not we've probably got some hardcore debugging to do - such is life with React Native.

@lucastbelem could you let me know what version of Android your phone is running?

**Comment by lucastbelem** [comment]
@JonEsparaz  I'm running Android 9 on Galaxy S8 - no forecast for getting the Android 10 on S8s yet. Apparently, 30% of android devices are running Android 9, so I'm wondering if we need to look into whether the issues are related to that?

**Comment by JonEsparaz** [comment]
I'll run some tests on Android 9 and see what's up.

**Comment by lucastbelem** [comment]
> * When creating an account, if I type my email and password and then select my location, once I do select the location, my email and password inputed disappear.

This issue seems to persist as of today on iOS as well.

**Comment by JonEsparaz** [comment]
> > * When creating an account, if I type my email and password and then select my location, once I do select the location, my email and password inputed disappear.
> 
> This issue seems to persist as of today on iOS as well.

I assume they are not on the latest version. This is certainly fixed.

**Comment by JonEsparaz** [comment]
> I'll run some tests on Android 9 and see what's up.

Android 9 works as expected - still can't reproduce.

**Comment by lucastbelem** [comment]
Ok. Let's sit tight on this. There is something else going on related to the version I have I think because I'm not getting the latest update at all. Working on George on the app store to solve it.

**Comment by lucastbelem** [comment]
> > > * When creating an account, if I type my email and password and then select my location, once I do select the location, my email and password inputed disappear.
> > 
> > 
> > This issue seems to persist as of today on iOS as well.
> 
> I assume they are not on the latest version. This is certainly fixed.

I just checked. Chris downloaded the latest release this morning before running tests. I'm stumped.

**Comment by JonEsparaz** [comment]
I assume with have a deployment/build issue then.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH maybe there is something on the iOS we need to look into as well.

**Comment by lucastbelem** [comment]
I feel good about closing this one now.
