### ISSUE TITLE
Should watch be selected by default on video page?

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/mobile#78]
Just wondering if we should make watch selected by default on the video page (but without the video auto-starting...clicking on the YouTube thumbnail or the watch button a second time could then start the video)...just seems like we miss out by not having the thumbnail...

**Comment by JonEsparaz** [comment]
@deeinstereo had the same thought. Will implement...

**Comment by deeinstereo** [comment]
Good catch boys! And just to triple confirm it won't autoplay, but it will just load the video and thumbnail by default.

**Comment by JonEsparaz** [comment]
I'll do this later this week (maybe on the weekend).
