### ISSUE TITLE
Update Icon

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/mobile#82]
Should be white background with black house icon.

**Comment by lucastbelem** [comment]
I changed this on Android, but can't seem to change it on iOS. It looks like the change needs to happen at the build level.

**Comment by lucastbelem** [comment]
Here is the file I used in case it's the same size.

![new_app_icons_2020](https://user-images.githubusercontent.com/48295718/94089442-3496fa00-fde1-11ea-9f60-7e8d6a41f17e.png)

**Comment by GeorgeBellTMH** [comment]
I need it as 1024x1024 png

On Sep 23, 2020, at 9:10 PM, Lucas Belem <notifications@github.com<mailto:notifications@github.com>> wrote:



Here is the file I used in case it's the same size.

[new_app_icons_2020]<https://user-images.githubusercontent.com/48295718/94089442-3496fa00-fde1-11ea-9f60-7e8d6a41f17e.png>

**Comment by deeinstereo** [comment]
@GeorgeBellTMH here you go! Built exactly to spec 
![TMH_App_Icon](https://user-images.githubusercontent.com/47831068/94162048-4bc2ff80-fe54-11ea-9693-9e12d3270cf8.png)

**Comment by GeorgeBellTMH** [comment]
It's in the next version!
