### ISSUE TITLE
Android app dashboard and testing

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#86]
I think something is still going on with the Android version. People who received the test link still only see the old app. This is what I see in the dashboard:
<img width="1440" alt="Screen Shot 2020-09-23 at 10 25 08 AM" src="https://user-images.githubusercontent.com/48295718/94026174-5499cf80-fd87-11ea-9146-fa8cd0a207f7.png">

**Comment by GeorgeBellTMH** [comment]
Ok this should work once the current app is reviewed by google.
