### ISSUE TITLE
Password creation

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/mobile#87]
Can we tell the user what their password parameters are?

**Comment by JonEsparaz** [comment]
Yeah I'll add this. I'm going to put it below the password field (but above the button). I'll make it such that the requirements turn green (or put a check mark or something) as they are met.

**Comment by lucastbelem** [comment]
@JonEsparaz the symbol parameter works, but displays incorrectly for the user. As soon as the user enters a number, both the number and symbol parameters change to green. But if the user doesn't enter a symbol, it tells them they need to enter one. It works, but it's confusing. Can we make sure that the symbol parameter only changes once a symbol is entered? 

Thanks.

**Comment by JonEsparaz** [comment]
Seems to only be an issue for 1,2,9,0, which is strange. I'll take a look.
