### ISSUE TITLE
Automatically Update API.ts

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#96]
When we make an API change in [themeetinghouse/web](https://github.com/themeetinghouse/web), it would be great if a PR was automatically created in this repo to update the file (via GitHub Actions probably).

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588046747)

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH would consider a monorepo? A lot of organizations do this for shared backends.

**Comment by georgevicbell** [comment]
I think it’s probably easier to just copy those files occasionally...it looks like there may be a way to have amplify codegen generate them from the endpoint as well. 

In practice we very rarely would have a breaking change in the API, it’s generally just additive outside of development. 

I’m not a fan of monorepo’s as they add a lot more churn and can be dependency multipliers.

**Comment by JonEsparaz** [comment]
Yup, monorepos don't always make sense.

If the plan is to manually update the file, I think we can close this issue.
