### ISSUE TITLE
Fix React Hooks warning

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/mobile#99]
This isn't a priority as it does _not_ affect end user, but should be fixed eventually.

The following warning is thrown whenever navigating to the [video player screen](https://github.com/themeetinghouse/mobile/blob/dev/screens/SermonLandingScreen.tsx): `"Cannot update a component from inside the function body of a different component."`

From the stack trace, I suspect the issue is that the [mini player](https://github.com/themeetinghouse/mobile/blob/dev/components/MiniPlayer.tsx) is always mounted and is constantly being updated via the `useContext()` hook, so we have components that are parallel in the component tree updating each other.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588046640)

**Comment by itbel** [comment]
This warning also occurs on NotesScreen.tsx
